#!/bin/bash
# This script generates a ascii art heading
# You need to install the tool figlet for this to work!
# apt-get install figlet
DOMAIN="voklab.ch"
echo "--------------------------------------------------------------------"
figlet -f slant "				$DOMAIN"
echo ""
echo "		https://$(ip -o addr show vmbr0.2 | awk '{print $4}' | head -n1 | awk -F"/" '{print $1}'):8006/"
echo "		https://$(hostname).$DOMAIN:8006/"
echo ""
echo "--------------------------------------------------------------------"
