#!/bin/bash
# This script prints basic system information
# Most of the script was created by yboetz
# https://github.com/yboetz/motd/blob/master/20-sysinfo
DOMAIN="example.com"

# get load averages
IFS=" " read -r LOAD1 LOAD5 LOAD15 <<<"$(awk '{ print $1,$2,$3 }' /proc/loadavg)"
# get free memory
IFS=" " read -r USED FREE TOTAL <<<"$(free -htm | grep "Mem" | awk {'print $3,$4,$2'})"
# get processes
PROCESS=$(ps -eo user=|sort|uniq -c | awk '{ print $2 " " $1 }')
PROCESS_ALL=$(echo "$PROCESS"| awk {'print $2'} | awk '{ SUM += $1} END { print SUM }')
PROCESS_ROOT=$(echo "$PROCESS"| grep root | awk {'print $2'})
PROCESS_USER=$(echo "$PROCESS"| grep -v root | awk {'print $2'} | awk '{ SUM += $1} END { print SUM }')
# get processors
PROCESSOR_NAME=$(grep "model name" /proc/cpuinfo | cut -d ' ' -f3- | awk {'print $0'} | head -1)
PROCESSOR_COUNT=$(grep -ioP 'processor\t:' /proc/cpuinfo | wc -l)

W="\\e[0;39m"
G="\\e[1;32m"

echo -e "
${W}SYSTEM INFO:
$W  FQDN........: $W"$(hostname).$DOMAIN"
$W  Distro......: $W$(cat /etc/*release | grep "PRETTY_NAME" | cut -d "=" -f 2- | sed 's/"//g')
$W  Kernel......: $W$(uname -sr) $(uname -v | sed -e 's/^.*(/(/')

$W  Uptime......: $W$(uptime -p)
$W  Current time: $W$(date)
$W  Online users: $W$(who|wc -l)

$W  Memory......: $G$USED$W used, $G$FREE$W free, $G$TOTAL$W total$W"

